---
name:   Olympians                   # The application display name
short:  Olympians                   # A shortened name for reference
appid:  olympians                   # Application identifier for Mac, iOS, Android
suffix: GAEE8E6C

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)

orientation: portrait               # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h
    - source/scenes/*.cpp
    - source/scenes/*.h
    - tests/**/*.cpp
    - tests/**/*.h
    - source/items/*.cpp
    - source/items/*.h
    - source/playerAI/*.cpp
    - source/playerAI/*.h
    - source/tests/*.cpp
    - source/tests/*.h

modules:
    - scene2

# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                        # The target platforms to build for
    - android                   # Android Studio
    - apple                     # XCode (note macOS and iOS use one project)
    - windows                   # Windows Sisual Studio
    - cmake                     # This supports all Desktop platform
